name: flutter_background_geolocation
description: The most sophisticated background location tracking & geofencing module with battery-conscious motion-detection intelligence for iOS and Android.
publish_to: none
version: 4.15.5
homepage: https://github.com/transistorsoft/flutter_background_geolocation

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  background_fetch:
    git:
      url: https://github.com/takashi11171117/flutter_background_fetch.git
      ref: master

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TSBackgroundGeolocationPlugin

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"
dev_dependencies:
  lints: ^3.0.0

